/*   Copyright (C) 2013-2014 Computer Sciences Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ezbake.data.mongo.driver.thrift;

import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class EzAggregationRequest implements org.apache.thrift.TBase<EzAggregationRequest, EzAggregationRequest._Fields>, java.io.Serializable, Cloneable, Comparable<EzAggregationRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("EzAggregationRequest");

  private static final org.apache.thrift.protocol.TField PIPELINE_FIELD_DESC = new org.apache.thrift.protocol.TField("pipeline", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField OPTIONS_FIELD_DESC = new org.apache.thrift.protocol.TField("options", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField READ_PREF_FIELD_DESC = new org.apache.thrift.protocol.TField("readPref", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new EzAggregationRequestStandardSchemeFactory());
    schemes.put(TupleScheme.class, new EzAggregationRequestTupleSchemeFactory());
  }

  public ByteBuffer pipeline; // required
  public ByteBuffer options; // required
  public ByteBuffer readPref; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PIPELINE((short)1, "pipeline"),
    OPTIONS((short)2, "options"),
    READ_PREF((short)3, "readPref");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PIPELINE
          return PIPELINE;
        case 2: // OPTIONS
          return OPTIONS;
        case 3: // READ_PREF
          return READ_PREF;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PIPELINE, new org.apache.thrift.meta_data.FieldMetaData("pipeline", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.OPTIONS, new org.apache.thrift.meta_data.FieldMetaData("options", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.READ_PREF, new org.apache.thrift.meta_data.FieldMetaData("readPref", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(EzAggregationRequest.class, metaDataMap);
  }

  public EzAggregationRequest() {
  }

  public EzAggregationRequest(
    ByteBuffer pipeline,
    ByteBuffer options,
    ByteBuffer readPref)
  {
    this();
    this.pipeline = pipeline;
    this.options = options;
    this.readPref = readPref;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public EzAggregationRequest(EzAggregationRequest other) {
    if (other.isSetPipeline()) {
      this.pipeline = org.apache.thrift.TBaseHelper.copyBinary(other.pipeline);
;
    }
    if (other.isSetOptions()) {
      this.options = org.apache.thrift.TBaseHelper.copyBinary(other.options);
;
    }
    if (other.isSetReadPref()) {
      this.readPref = org.apache.thrift.TBaseHelper.copyBinary(other.readPref);
;
    }
  }

  public EzAggregationRequest deepCopy() {
    return new EzAggregationRequest(this);
  }

  @Override
  public void clear() {
    this.pipeline = null;
    this.options = null;
    this.readPref = null;
  }

  public byte[] getPipeline() {
    setPipeline(org.apache.thrift.TBaseHelper.rightSize(pipeline));
    return pipeline == null ? null : pipeline.array();
  }

  public ByteBuffer bufferForPipeline() {
    return pipeline;
  }

  public EzAggregationRequest setPipeline(byte[] pipeline) {
    setPipeline(pipeline == null ? (ByteBuffer)null : ByteBuffer.wrap(pipeline));
    return this;
  }

  public EzAggregationRequest setPipeline(ByteBuffer pipeline) {
    this.pipeline = pipeline;
    return this;
  }

  public void unsetPipeline() {
    this.pipeline = null;
  }

  /** Returns true if field pipeline is set (has been assigned a value) and false otherwise */
  public boolean isSetPipeline() {
    return this.pipeline != null;
  }

  public void setPipelineIsSet(boolean value) {
    if (!value) {
      this.pipeline = null;
    }
  }

  public byte[] getOptions() {
    setOptions(org.apache.thrift.TBaseHelper.rightSize(options));
    return options == null ? null : options.array();
  }

  public ByteBuffer bufferForOptions() {
    return options;
  }

  public EzAggregationRequest setOptions(byte[] options) {
    setOptions(options == null ? (ByteBuffer)null : ByteBuffer.wrap(options));
    return this;
  }

  public EzAggregationRequest setOptions(ByteBuffer options) {
    this.options = options;
    return this;
  }

  public void unsetOptions() {
    this.options = null;
  }

  /** Returns true if field options is set (has been assigned a value) and false otherwise */
  public boolean isSetOptions() {
    return this.options != null;
  }

  public void setOptionsIsSet(boolean value) {
    if (!value) {
      this.options = null;
    }
  }

  public byte[] getReadPref() {
    setReadPref(org.apache.thrift.TBaseHelper.rightSize(readPref));
    return readPref == null ? null : readPref.array();
  }

  public ByteBuffer bufferForReadPref() {
    return readPref;
  }

  public EzAggregationRequest setReadPref(byte[] readPref) {
    setReadPref(readPref == null ? (ByteBuffer)null : ByteBuffer.wrap(readPref));
    return this;
  }

  public EzAggregationRequest setReadPref(ByteBuffer readPref) {
    this.readPref = readPref;
    return this;
  }

  public void unsetReadPref() {
    this.readPref = null;
  }

  /** Returns true if field readPref is set (has been assigned a value) and false otherwise */
  public boolean isSetReadPref() {
    return this.readPref != null;
  }

  public void setReadPrefIsSet(boolean value) {
    if (!value) {
      this.readPref = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PIPELINE:
      if (value == null) {
        unsetPipeline();
      } else {
        setPipeline((ByteBuffer)value);
      }
      break;

    case OPTIONS:
      if (value == null) {
        unsetOptions();
      } else {
        setOptions((ByteBuffer)value);
      }
      break;

    case READ_PREF:
      if (value == null) {
        unsetReadPref();
      } else {
        setReadPref((ByteBuffer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PIPELINE:
      return getPipeline();

    case OPTIONS:
      return getOptions();

    case READ_PREF:
      return getReadPref();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PIPELINE:
      return isSetPipeline();
    case OPTIONS:
      return isSetOptions();
    case READ_PREF:
      return isSetReadPref();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof EzAggregationRequest)
      return this.equals((EzAggregationRequest)that);
    return false;
  }

  public boolean equals(EzAggregationRequest that) {
    if (that == null)
      return false;

    boolean this_present_pipeline = true && this.isSetPipeline();
    boolean that_present_pipeline = true && that.isSetPipeline();
    if (this_present_pipeline || that_present_pipeline) {
      if (!(this_present_pipeline && that_present_pipeline))
        return false;
      if (!this.pipeline.equals(that.pipeline))
        return false;
    }

    boolean this_present_options = true && this.isSetOptions();
    boolean that_present_options = true && that.isSetOptions();
    if (this_present_options || that_present_options) {
      if (!(this_present_options && that_present_options))
        return false;
      if (!this.options.equals(that.options))
        return false;
    }

    boolean this_present_readPref = true && this.isSetReadPref();
    boolean that_present_readPref = true && that.isSetReadPref();
    if (this_present_readPref || that_present_readPref) {
      if (!(this_present_readPref && that_present_readPref))
        return false;
      if (!this.readPref.equals(that.readPref))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_pipeline = true && (isSetPipeline());
    builder.append(present_pipeline);
    if (present_pipeline)
      builder.append(pipeline);

    boolean present_options = true && (isSetOptions());
    builder.append(present_options);
    if (present_options)
      builder.append(options);

    boolean present_readPref = true && (isSetReadPref());
    builder.append(present_readPref);
    if (present_readPref)
      builder.append(readPref);

    return builder.toHashCode();
  }

  @Override
  public int compareTo(EzAggregationRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPipeline()).compareTo(other.isSetPipeline());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPipeline()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pipeline, other.pipeline);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOptions()).compareTo(other.isSetOptions());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOptions()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.options, other.options);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetReadPref()).compareTo(other.isSetReadPref());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReadPref()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.readPref, other.readPref);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("EzAggregationRequest(");
    boolean first = true;

    sb.append("pipeline:");
    if (this.pipeline == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.pipeline, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("options:");
    if (this.options == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.options, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("readPref:");
    if (this.readPref == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.readPref, sb);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class EzAggregationRequestStandardSchemeFactory implements SchemeFactory {
    public EzAggregationRequestStandardScheme getScheme() {
      return new EzAggregationRequestStandardScheme();
    }
  }

  private static class EzAggregationRequestStandardScheme extends StandardScheme<EzAggregationRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, EzAggregationRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PIPELINE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.pipeline = iprot.readBinary();
              struct.setPipelineIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // OPTIONS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.options = iprot.readBinary();
              struct.setOptionsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // READ_PREF
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.readPref = iprot.readBinary();
              struct.setReadPrefIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, EzAggregationRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.pipeline != null) {
        oprot.writeFieldBegin(PIPELINE_FIELD_DESC);
        oprot.writeBinary(struct.pipeline);
        oprot.writeFieldEnd();
      }
      if (struct.options != null) {
        oprot.writeFieldBegin(OPTIONS_FIELD_DESC);
        oprot.writeBinary(struct.options);
        oprot.writeFieldEnd();
      }
      if (struct.readPref != null) {
        oprot.writeFieldBegin(READ_PREF_FIELD_DESC);
        oprot.writeBinary(struct.readPref);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class EzAggregationRequestTupleSchemeFactory implements SchemeFactory {
    public EzAggregationRequestTupleScheme getScheme() {
      return new EzAggregationRequestTupleScheme();
    }
  }

  private static class EzAggregationRequestTupleScheme extends TupleScheme<EzAggregationRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, EzAggregationRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPipeline()) {
        optionals.set(0);
      }
      if (struct.isSetOptions()) {
        optionals.set(1);
      }
      if (struct.isSetReadPref()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetPipeline()) {
        oprot.writeBinary(struct.pipeline);
      }
      if (struct.isSetOptions()) {
        oprot.writeBinary(struct.options);
      }
      if (struct.isSetReadPref()) {
        oprot.writeBinary(struct.readPref);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, EzAggregationRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.pipeline = iprot.readBinary();
        struct.setPipelineIsSet(true);
      }
      if (incoming.get(1)) {
        struct.options = iprot.readBinary();
        struct.setOptionsIsSet(true);
      }
      if (incoming.get(2)) {
        struct.readPref = iprot.readBinary();
        struct.setReadPrefIsSet(true);
      }
    }
  }

}

