/*   Copyright (C) 2013-2014 Computer Sciences Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ezbake.data.mongo.driver.thrift;

import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class EzGetMoreResponse implements org.apache.thrift.TBase<EzGetMoreResponse, EzGetMoreResponse._Fields>, java.io.Serializable, Cloneable, Comparable<EzGetMoreResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("EzGetMoreResponse");

  private static final org.apache.thrift.protocol.TField RESPONSE_FIELD_DESC = new org.apache.thrift.protocol.TField("response", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField RESULT_SET_FIELD_DESC = new org.apache.thrift.protocol.TField("resultSet", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField MONGOEXCEPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("mongoexception", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new EzGetMoreResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new EzGetMoreResponseTupleSchemeFactory());
  }

  public ByteBuffer response; // required
  public ByteBuffer resultSet; // required
  public ByteBuffer mongoexception; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RESPONSE((short)1, "response"),
    RESULT_SET((short)2, "resultSet"),
    MONGOEXCEPTION((short)3, "mongoexception");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RESPONSE
          return RESPONSE;
        case 2: // RESULT_SET
          return RESULT_SET;
        case 3: // MONGOEXCEPTION
          return MONGOEXCEPTION;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.MONGOEXCEPTION};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RESPONSE, new org.apache.thrift.meta_data.FieldMetaData("response", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.RESULT_SET, new org.apache.thrift.meta_data.FieldMetaData("resultSet", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.MONGOEXCEPTION, new org.apache.thrift.meta_data.FieldMetaData("mongoexception", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(EzGetMoreResponse.class, metaDataMap);
  }

  public EzGetMoreResponse() {
  }

  public EzGetMoreResponse(
    ByteBuffer response,
    ByteBuffer resultSet)
  {
    this();
    this.response = response;
    this.resultSet = resultSet;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public EzGetMoreResponse(EzGetMoreResponse other) {
    if (other.isSetResponse()) {
      this.response = org.apache.thrift.TBaseHelper.copyBinary(other.response);
;
    }
    if (other.isSetResultSet()) {
      this.resultSet = org.apache.thrift.TBaseHelper.copyBinary(other.resultSet);
;
    }
    if (other.isSetMongoexception()) {
      this.mongoexception = org.apache.thrift.TBaseHelper.copyBinary(other.mongoexception);
;
    }
  }

  public EzGetMoreResponse deepCopy() {
    return new EzGetMoreResponse(this);
  }

  @Override
  public void clear() {
    this.response = null;
    this.resultSet = null;
    this.mongoexception = null;
  }

  public byte[] getResponse() {
    setResponse(org.apache.thrift.TBaseHelper.rightSize(response));
    return response == null ? null : response.array();
  }

  public ByteBuffer bufferForResponse() {
    return response;
  }

  public EzGetMoreResponse setResponse(byte[] response) {
    setResponse(response == null ? (ByteBuffer)null : ByteBuffer.wrap(response));
    return this;
  }

  public EzGetMoreResponse setResponse(ByteBuffer response) {
    this.response = response;
    return this;
  }

  public void unsetResponse() {
    this.response = null;
  }

  /** Returns true if field response is set (has been assigned a value) and false otherwise */
  public boolean isSetResponse() {
    return this.response != null;
  }

  public void setResponseIsSet(boolean value) {
    if (!value) {
      this.response = null;
    }
  }

  public byte[] getResultSet() {
    setResultSet(org.apache.thrift.TBaseHelper.rightSize(resultSet));
    return resultSet == null ? null : resultSet.array();
  }

  public ByteBuffer bufferForResultSet() {
    return resultSet;
  }

  public EzGetMoreResponse setResultSet(byte[] resultSet) {
    setResultSet(resultSet == null ? (ByteBuffer)null : ByteBuffer.wrap(resultSet));
    return this;
  }

  public EzGetMoreResponse setResultSet(ByteBuffer resultSet) {
    this.resultSet = resultSet;
    return this;
  }

  public void unsetResultSet() {
    this.resultSet = null;
  }

  /** Returns true if field resultSet is set (has been assigned a value) and false otherwise */
  public boolean isSetResultSet() {
    return this.resultSet != null;
  }

  public void setResultSetIsSet(boolean value) {
    if (!value) {
      this.resultSet = null;
    }
  }

  public byte[] getMongoexception() {
    setMongoexception(org.apache.thrift.TBaseHelper.rightSize(mongoexception));
    return mongoexception == null ? null : mongoexception.array();
  }

  public ByteBuffer bufferForMongoexception() {
    return mongoexception;
  }

  public EzGetMoreResponse setMongoexception(byte[] mongoexception) {
    setMongoexception(mongoexception == null ? (ByteBuffer)null : ByteBuffer.wrap(mongoexception));
    return this;
  }

  public EzGetMoreResponse setMongoexception(ByteBuffer mongoexception) {
    this.mongoexception = mongoexception;
    return this;
  }

  public void unsetMongoexception() {
    this.mongoexception = null;
  }

  /** Returns true if field mongoexception is set (has been assigned a value) and false otherwise */
  public boolean isSetMongoexception() {
    return this.mongoexception != null;
  }

  public void setMongoexceptionIsSet(boolean value) {
    if (!value) {
      this.mongoexception = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RESPONSE:
      if (value == null) {
        unsetResponse();
      } else {
        setResponse((ByteBuffer)value);
      }
      break;

    case RESULT_SET:
      if (value == null) {
        unsetResultSet();
      } else {
        setResultSet((ByteBuffer)value);
      }
      break;

    case MONGOEXCEPTION:
      if (value == null) {
        unsetMongoexception();
      } else {
        setMongoexception((ByteBuffer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RESPONSE:
      return getResponse();

    case RESULT_SET:
      return getResultSet();

    case MONGOEXCEPTION:
      return getMongoexception();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RESPONSE:
      return isSetResponse();
    case RESULT_SET:
      return isSetResultSet();
    case MONGOEXCEPTION:
      return isSetMongoexception();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof EzGetMoreResponse)
      return this.equals((EzGetMoreResponse)that);
    return false;
  }

  public boolean equals(EzGetMoreResponse that) {
    if (that == null)
      return false;

    boolean this_present_response = true && this.isSetResponse();
    boolean that_present_response = true && that.isSetResponse();
    if (this_present_response || that_present_response) {
      if (!(this_present_response && that_present_response))
        return false;
      if (!this.response.equals(that.response))
        return false;
    }

    boolean this_present_resultSet = true && this.isSetResultSet();
    boolean that_present_resultSet = true && that.isSetResultSet();
    if (this_present_resultSet || that_present_resultSet) {
      if (!(this_present_resultSet && that_present_resultSet))
        return false;
      if (!this.resultSet.equals(that.resultSet))
        return false;
    }

    boolean this_present_mongoexception = true && this.isSetMongoexception();
    boolean that_present_mongoexception = true && that.isSetMongoexception();
    if (this_present_mongoexception || that_present_mongoexception) {
      if (!(this_present_mongoexception && that_present_mongoexception))
        return false;
      if (!this.mongoexception.equals(that.mongoexception))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_response = true && (isSetResponse());
    builder.append(present_response);
    if (present_response)
      builder.append(response);

    boolean present_resultSet = true && (isSetResultSet());
    builder.append(present_resultSet);
    if (present_resultSet)
      builder.append(resultSet);

    boolean present_mongoexception = true && (isSetMongoexception());
    builder.append(present_mongoexception);
    if (present_mongoexception)
      builder.append(mongoexception);

    return builder.toHashCode();
  }

  @Override
  public int compareTo(EzGetMoreResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetResponse()).compareTo(other.isSetResponse());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResponse()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.response, other.response);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetResultSet()).compareTo(other.isSetResultSet());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResultSet()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.resultSet, other.resultSet);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMongoexception()).compareTo(other.isSetMongoexception());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMongoexception()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mongoexception, other.mongoexception);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("EzGetMoreResponse(");
    boolean first = true;

    sb.append("response:");
    if (this.response == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.response, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("resultSet:");
    if (this.resultSet == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.resultSet, sb);
    }
    first = false;
    if (isSetMongoexception()) {
      if (!first) sb.append(", ");
      sb.append("mongoexception:");
      if (this.mongoexception == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.mongoexception, sb);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class EzGetMoreResponseStandardSchemeFactory implements SchemeFactory {
    public EzGetMoreResponseStandardScheme getScheme() {
      return new EzGetMoreResponseStandardScheme();
    }
  }

  private static class EzGetMoreResponseStandardScheme extends StandardScheme<EzGetMoreResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, EzGetMoreResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RESPONSE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.response = iprot.readBinary();
              struct.setResponseIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RESULT_SET
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.resultSet = iprot.readBinary();
              struct.setResultSetIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // MONGOEXCEPTION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.mongoexception = iprot.readBinary();
              struct.setMongoexceptionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, EzGetMoreResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.response != null) {
        oprot.writeFieldBegin(RESPONSE_FIELD_DESC);
        oprot.writeBinary(struct.response);
        oprot.writeFieldEnd();
      }
      if (struct.resultSet != null) {
        oprot.writeFieldBegin(RESULT_SET_FIELD_DESC);
        oprot.writeBinary(struct.resultSet);
        oprot.writeFieldEnd();
      }
      if (struct.mongoexception != null) {
        if (struct.isSetMongoexception()) {
          oprot.writeFieldBegin(MONGOEXCEPTION_FIELD_DESC);
          oprot.writeBinary(struct.mongoexception);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class EzGetMoreResponseTupleSchemeFactory implements SchemeFactory {
    public EzGetMoreResponseTupleScheme getScheme() {
      return new EzGetMoreResponseTupleScheme();
    }
  }

  private static class EzGetMoreResponseTupleScheme extends TupleScheme<EzGetMoreResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, EzGetMoreResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetResponse()) {
        optionals.set(0);
      }
      if (struct.isSetResultSet()) {
        optionals.set(1);
      }
      if (struct.isSetMongoexception()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetResponse()) {
        oprot.writeBinary(struct.response);
      }
      if (struct.isSetResultSet()) {
        oprot.writeBinary(struct.resultSet);
      }
      if (struct.isSetMongoexception()) {
        oprot.writeBinary(struct.mongoexception);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, EzGetMoreResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.response = iprot.readBinary();
        struct.setResponseIsSet(true);
      }
      if (incoming.get(1)) {
        struct.resultSet = iprot.readBinary();
        struct.setResultSetIsSet(true);
      }
      if (incoming.get(2)) {
        struct.mongoexception = iprot.readBinary();
        struct.setMongoexceptionIsSet(true);
      }
    }
  }

}

