/*   Copyright (C) 2013-2014 Computer Sciences Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ezbake.data.mongo.driver.thrift;

import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class EzUpdateRequest implements org.apache.thrift.TBase<EzUpdateRequest, EzUpdateRequest._Fields>, java.io.Serializable, Cloneable, Comparable<EzUpdateRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("EzUpdateRequest");

  private static final org.apache.thrift.protocol.TField QUERY_FIELD_DESC = new org.apache.thrift.protocol.TField("query", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField DB_UPDATE_OBJECT_FIELD_DESC = new org.apache.thrift.protocol.TField("dbUpdateObject", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField UPSERT_FIELD_DESC = new org.apache.thrift.protocol.TField("upsert", org.apache.thrift.protocol.TType.BOOL, (short)3);
  private static final org.apache.thrift.protocol.TField MULTI_FIELD_DESC = new org.apache.thrift.protocol.TField("multi", org.apache.thrift.protocol.TType.BOOL, (short)4);
  private static final org.apache.thrift.protocol.TField WRITE_CONCERN_FIELD_DESC = new org.apache.thrift.protocol.TField("writeConcern", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField DB_ENCODER_FIELD_DESC = new org.apache.thrift.protocol.TField("dbEncoder", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField IS_UNIT_TEST_MODE_FIELD_DESC = new org.apache.thrift.protocol.TField("isUnitTestMode", org.apache.thrift.protocol.TType.BOOL, (short)7);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new EzUpdateRequestStandardSchemeFactory());
    schemes.put(TupleScheme.class, new EzUpdateRequestTupleSchemeFactory());
  }

  public ByteBuffer query; // required
  public ByteBuffer dbUpdateObject; // required
  public boolean upsert; // required
  public boolean multi; // required
  public ByteBuffer writeConcern; // required
  public ByteBuffer dbEncoder; // required
  public boolean isUnitTestMode; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    QUERY((short)1, "query"),
    DB_UPDATE_OBJECT((short)2, "dbUpdateObject"),
    UPSERT((short)3, "upsert"),
    MULTI((short)4, "multi"),
    WRITE_CONCERN((short)5, "writeConcern"),
    DB_ENCODER((short)6, "dbEncoder"),
    IS_UNIT_TEST_MODE((short)7, "isUnitTestMode");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // QUERY
          return QUERY;
        case 2: // DB_UPDATE_OBJECT
          return DB_UPDATE_OBJECT;
        case 3: // UPSERT
          return UPSERT;
        case 4: // MULTI
          return MULTI;
        case 5: // WRITE_CONCERN
          return WRITE_CONCERN;
        case 6: // DB_ENCODER
          return DB_ENCODER;
        case 7: // IS_UNIT_TEST_MODE
          return IS_UNIT_TEST_MODE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __UPSERT_ISSET_ID = 0;
  private static final int __MULTI_ISSET_ID = 1;
  private static final int __ISUNITTESTMODE_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.QUERY, new org.apache.thrift.meta_data.FieldMetaData("query", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.DB_UPDATE_OBJECT, new org.apache.thrift.meta_data.FieldMetaData("dbUpdateObject", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.UPSERT, new org.apache.thrift.meta_data.FieldMetaData("upsert", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.MULTI, new org.apache.thrift.meta_data.FieldMetaData("multi", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.WRITE_CONCERN, new org.apache.thrift.meta_data.FieldMetaData("writeConcern", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.DB_ENCODER, new org.apache.thrift.meta_data.FieldMetaData("dbEncoder", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.IS_UNIT_TEST_MODE, new org.apache.thrift.meta_data.FieldMetaData("isUnitTestMode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(EzUpdateRequest.class, metaDataMap);
  }

  public EzUpdateRequest() {
  }

  public EzUpdateRequest(
    ByteBuffer query,
    ByteBuffer dbUpdateObject,
    boolean upsert,
    boolean multi,
    ByteBuffer writeConcern,
    ByteBuffer dbEncoder,
    boolean isUnitTestMode)
  {
    this();
    this.query = query;
    this.dbUpdateObject = dbUpdateObject;
    this.upsert = upsert;
    setUpsertIsSet(true);
    this.multi = multi;
    setMultiIsSet(true);
    this.writeConcern = writeConcern;
    this.dbEncoder = dbEncoder;
    this.isUnitTestMode = isUnitTestMode;
    setIsUnitTestModeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public EzUpdateRequest(EzUpdateRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetQuery()) {
      this.query = org.apache.thrift.TBaseHelper.copyBinary(other.query);
;
    }
    if (other.isSetDbUpdateObject()) {
      this.dbUpdateObject = org.apache.thrift.TBaseHelper.copyBinary(other.dbUpdateObject);
;
    }
    this.upsert = other.upsert;
    this.multi = other.multi;
    if (other.isSetWriteConcern()) {
      this.writeConcern = org.apache.thrift.TBaseHelper.copyBinary(other.writeConcern);
;
    }
    if (other.isSetDbEncoder()) {
      this.dbEncoder = org.apache.thrift.TBaseHelper.copyBinary(other.dbEncoder);
;
    }
    this.isUnitTestMode = other.isUnitTestMode;
  }

  public EzUpdateRequest deepCopy() {
    return new EzUpdateRequest(this);
  }

  @Override
  public void clear() {
    this.query = null;
    this.dbUpdateObject = null;
    setUpsertIsSet(false);
    this.upsert = false;
    setMultiIsSet(false);
    this.multi = false;
    this.writeConcern = null;
    this.dbEncoder = null;
    setIsUnitTestModeIsSet(false);
    this.isUnitTestMode = false;
  }

  public byte[] getQuery() {
    setQuery(org.apache.thrift.TBaseHelper.rightSize(query));
    return query == null ? null : query.array();
  }

  public ByteBuffer bufferForQuery() {
    return query;
  }

  public EzUpdateRequest setQuery(byte[] query) {
    setQuery(query == null ? (ByteBuffer)null : ByteBuffer.wrap(query));
    return this;
  }

  public EzUpdateRequest setQuery(ByteBuffer query) {
    this.query = query;
    return this;
  }

  public void unsetQuery() {
    this.query = null;
  }

  /** Returns true if field query is set (has been assigned a value) and false otherwise */
  public boolean isSetQuery() {
    return this.query != null;
  }

  public void setQueryIsSet(boolean value) {
    if (!value) {
      this.query = null;
    }
  }

  public byte[] getDbUpdateObject() {
    setDbUpdateObject(org.apache.thrift.TBaseHelper.rightSize(dbUpdateObject));
    return dbUpdateObject == null ? null : dbUpdateObject.array();
  }

  public ByteBuffer bufferForDbUpdateObject() {
    return dbUpdateObject;
  }

  public EzUpdateRequest setDbUpdateObject(byte[] dbUpdateObject) {
    setDbUpdateObject(dbUpdateObject == null ? (ByteBuffer)null : ByteBuffer.wrap(dbUpdateObject));
    return this;
  }

  public EzUpdateRequest setDbUpdateObject(ByteBuffer dbUpdateObject) {
    this.dbUpdateObject = dbUpdateObject;
    return this;
  }

  public void unsetDbUpdateObject() {
    this.dbUpdateObject = null;
  }

  /** Returns true if field dbUpdateObject is set (has been assigned a value) and false otherwise */
  public boolean isSetDbUpdateObject() {
    return this.dbUpdateObject != null;
  }

  public void setDbUpdateObjectIsSet(boolean value) {
    if (!value) {
      this.dbUpdateObject = null;
    }
  }

  public boolean isUpsert() {
    return this.upsert;
  }

  public EzUpdateRequest setUpsert(boolean upsert) {
    this.upsert = upsert;
    setUpsertIsSet(true);
    return this;
  }

  public void unsetUpsert() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __UPSERT_ISSET_ID);
  }

  /** Returns true if field upsert is set (has been assigned a value) and false otherwise */
  public boolean isSetUpsert() {
    return EncodingUtils.testBit(__isset_bitfield, __UPSERT_ISSET_ID);
  }

  public void setUpsertIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __UPSERT_ISSET_ID, value);
  }

  public boolean isMulti() {
    return this.multi;
  }

  public EzUpdateRequest setMulti(boolean multi) {
    this.multi = multi;
    setMultiIsSet(true);
    return this;
  }

  public void unsetMulti() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __MULTI_ISSET_ID);
  }

  /** Returns true if field multi is set (has been assigned a value) and false otherwise */
  public boolean isSetMulti() {
    return EncodingUtils.testBit(__isset_bitfield, __MULTI_ISSET_ID);
  }

  public void setMultiIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __MULTI_ISSET_ID, value);
  }

  public byte[] getWriteConcern() {
    setWriteConcern(org.apache.thrift.TBaseHelper.rightSize(writeConcern));
    return writeConcern == null ? null : writeConcern.array();
  }

  public ByteBuffer bufferForWriteConcern() {
    return writeConcern;
  }

  public EzUpdateRequest setWriteConcern(byte[] writeConcern) {
    setWriteConcern(writeConcern == null ? (ByteBuffer)null : ByteBuffer.wrap(writeConcern));
    return this;
  }

  public EzUpdateRequest setWriteConcern(ByteBuffer writeConcern) {
    this.writeConcern = writeConcern;
    return this;
  }

  public void unsetWriteConcern() {
    this.writeConcern = null;
  }

  /** Returns true if field writeConcern is set (has been assigned a value) and false otherwise */
  public boolean isSetWriteConcern() {
    return this.writeConcern != null;
  }

  public void setWriteConcernIsSet(boolean value) {
    if (!value) {
      this.writeConcern = null;
    }
  }

  public byte[] getDbEncoder() {
    setDbEncoder(org.apache.thrift.TBaseHelper.rightSize(dbEncoder));
    return dbEncoder == null ? null : dbEncoder.array();
  }

  public ByteBuffer bufferForDbEncoder() {
    return dbEncoder;
  }

  public EzUpdateRequest setDbEncoder(byte[] dbEncoder) {
    setDbEncoder(dbEncoder == null ? (ByteBuffer)null : ByteBuffer.wrap(dbEncoder));
    return this;
  }

  public EzUpdateRequest setDbEncoder(ByteBuffer dbEncoder) {
    this.dbEncoder = dbEncoder;
    return this;
  }

  public void unsetDbEncoder() {
    this.dbEncoder = null;
  }

  /** Returns true if field dbEncoder is set (has been assigned a value) and false otherwise */
  public boolean isSetDbEncoder() {
    return this.dbEncoder != null;
  }

  public void setDbEncoderIsSet(boolean value) {
    if (!value) {
      this.dbEncoder = null;
    }
  }

  public boolean isIsUnitTestMode() {
    return this.isUnitTestMode;
  }

  public EzUpdateRequest setIsUnitTestMode(boolean isUnitTestMode) {
    this.isUnitTestMode = isUnitTestMode;
    setIsUnitTestModeIsSet(true);
    return this;
  }

  public void unsetIsUnitTestMode() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ISUNITTESTMODE_ISSET_ID);
  }

  /** Returns true if field isUnitTestMode is set (has been assigned a value) and false otherwise */
  public boolean isSetIsUnitTestMode() {
    return EncodingUtils.testBit(__isset_bitfield, __ISUNITTESTMODE_ISSET_ID);
  }

  public void setIsUnitTestModeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ISUNITTESTMODE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case QUERY:
      if (value == null) {
        unsetQuery();
      } else {
        setQuery((ByteBuffer)value);
      }
      break;

    case DB_UPDATE_OBJECT:
      if (value == null) {
        unsetDbUpdateObject();
      } else {
        setDbUpdateObject((ByteBuffer)value);
      }
      break;

    case UPSERT:
      if (value == null) {
        unsetUpsert();
      } else {
        setUpsert((Boolean)value);
      }
      break;

    case MULTI:
      if (value == null) {
        unsetMulti();
      } else {
        setMulti((Boolean)value);
      }
      break;

    case WRITE_CONCERN:
      if (value == null) {
        unsetWriteConcern();
      } else {
        setWriteConcern((ByteBuffer)value);
      }
      break;

    case DB_ENCODER:
      if (value == null) {
        unsetDbEncoder();
      } else {
        setDbEncoder((ByteBuffer)value);
      }
      break;

    case IS_UNIT_TEST_MODE:
      if (value == null) {
        unsetIsUnitTestMode();
      } else {
        setIsUnitTestMode((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case QUERY:
      return getQuery();

    case DB_UPDATE_OBJECT:
      return getDbUpdateObject();

    case UPSERT:
      return Boolean.valueOf(isUpsert());

    case MULTI:
      return Boolean.valueOf(isMulti());

    case WRITE_CONCERN:
      return getWriteConcern();

    case DB_ENCODER:
      return getDbEncoder();

    case IS_UNIT_TEST_MODE:
      return Boolean.valueOf(isIsUnitTestMode());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case QUERY:
      return isSetQuery();
    case DB_UPDATE_OBJECT:
      return isSetDbUpdateObject();
    case UPSERT:
      return isSetUpsert();
    case MULTI:
      return isSetMulti();
    case WRITE_CONCERN:
      return isSetWriteConcern();
    case DB_ENCODER:
      return isSetDbEncoder();
    case IS_UNIT_TEST_MODE:
      return isSetIsUnitTestMode();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof EzUpdateRequest)
      return this.equals((EzUpdateRequest)that);
    return false;
  }

  public boolean equals(EzUpdateRequest that) {
    if (that == null)
      return false;

    boolean this_present_query = true && this.isSetQuery();
    boolean that_present_query = true && that.isSetQuery();
    if (this_present_query || that_present_query) {
      if (!(this_present_query && that_present_query))
        return false;
      if (!this.query.equals(that.query))
        return false;
    }

    boolean this_present_dbUpdateObject = true && this.isSetDbUpdateObject();
    boolean that_present_dbUpdateObject = true && that.isSetDbUpdateObject();
    if (this_present_dbUpdateObject || that_present_dbUpdateObject) {
      if (!(this_present_dbUpdateObject && that_present_dbUpdateObject))
        return false;
      if (!this.dbUpdateObject.equals(that.dbUpdateObject))
        return false;
    }

    boolean this_present_upsert = true;
    boolean that_present_upsert = true;
    if (this_present_upsert || that_present_upsert) {
      if (!(this_present_upsert && that_present_upsert))
        return false;
      if (this.upsert != that.upsert)
        return false;
    }

    boolean this_present_multi = true;
    boolean that_present_multi = true;
    if (this_present_multi || that_present_multi) {
      if (!(this_present_multi && that_present_multi))
        return false;
      if (this.multi != that.multi)
        return false;
    }

    boolean this_present_writeConcern = true && this.isSetWriteConcern();
    boolean that_present_writeConcern = true && that.isSetWriteConcern();
    if (this_present_writeConcern || that_present_writeConcern) {
      if (!(this_present_writeConcern && that_present_writeConcern))
        return false;
      if (!this.writeConcern.equals(that.writeConcern))
        return false;
    }

    boolean this_present_dbEncoder = true && this.isSetDbEncoder();
    boolean that_present_dbEncoder = true && that.isSetDbEncoder();
    if (this_present_dbEncoder || that_present_dbEncoder) {
      if (!(this_present_dbEncoder && that_present_dbEncoder))
        return false;
      if (!this.dbEncoder.equals(that.dbEncoder))
        return false;
    }

    boolean this_present_isUnitTestMode = true;
    boolean that_present_isUnitTestMode = true;
    if (this_present_isUnitTestMode || that_present_isUnitTestMode) {
      if (!(this_present_isUnitTestMode && that_present_isUnitTestMode))
        return false;
      if (this.isUnitTestMode != that.isUnitTestMode)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_query = true && (isSetQuery());
    builder.append(present_query);
    if (present_query)
      builder.append(query);

    boolean present_dbUpdateObject = true && (isSetDbUpdateObject());
    builder.append(present_dbUpdateObject);
    if (present_dbUpdateObject)
      builder.append(dbUpdateObject);

    boolean present_upsert = true;
    builder.append(present_upsert);
    if (present_upsert)
      builder.append(upsert);

    boolean present_multi = true;
    builder.append(present_multi);
    if (present_multi)
      builder.append(multi);

    boolean present_writeConcern = true && (isSetWriteConcern());
    builder.append(present_writeConcern);
    if (present_writeConcern)
      builder.append(writeConcern);

    boolean present_dbEncoder = true && (isSetDbEncoder());
    builder.append(present_dbEncoder);
    if (present_dbEncoder)
      builder.append(dbEncoder);

    boolean present_isUnitTestMode = true;
    builder.append(present_isUnitTestMode);
    if (present_isUnitTestMode)
      builder.append(isUnitTestMode);

    return builder.toHashCode();
  }

  @Override
  public int compareTo(EzUpdateRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetQuery()).compareTo(other.isSetQuery());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQuery()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.query, other.query);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDbUpdateObject()).compareTo(other.isSetDbUpdateObject());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDbUpdateObject()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dbUpdateObject, other.dbUpdateObject);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUpsert()).compareTo(other.isSetUpsert());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUpsert()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.upsert, other.upsert);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMulti()).compareTo(other.isSetMulti());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMulti()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.multi, other.multi);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetWriteConcern()).compareTo(other.isSetWriteConcern());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWriteConcern()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.writeConcern, other.writeConcern);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDbEncoder()).compareTo(other.isSetDbEncoder());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDbEncoder()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dbEncoder, other.dbEncoder);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIsUnitTestMode()).compareTo(other.isSetIsUnitTestMode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsUnitTestMode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isUnitTestMode, other.isUnitTestMode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("EzUpdateRequest(");
    boolean first = true;

    sb.append("query:");
    if (this.query == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.query, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("dbUpdateObject:");
    if (this.dbUpdateObject == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.dbUpdateObject, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("upsert:");
    sb.append(this.upsert);
    first = false;
    if (!first) sb.append(", ");
    sb.append("multi:");
    sb.append(this.multi);
    first = false;
    if (!first) sb.append(", ");
    sb.append("writeConcern:");
    if (this.writeConcern == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.writeConcern, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("dbEncoder:");
    if (this.dbEncoder == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.dbEncoder, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("isUnitTestMode:");
    sb.append(this.isUnitTestMode);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class EzUpdateRequestStandardSchemeFactory implements SchemeFactory {
    public EzUpdateRequestStandardScheme getScheme() {
      return new EzUpdateRequestStandardScheme();
    }
  }

  private static class EzUpdateRequestStandardScheme extends StandardScheme<EzUpdateRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, EzUpdateRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // QUERY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.query = iprot.readBinary();
              struct.setQueryIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DB_UPDATE_OBJECT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.dbUpdateObject = iprot.readBinary();
              struct.setDbUpdateObjectIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // UPSERT
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.upsert = iprot.readBool();
              struct.setUpsertIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // MULTI
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.multi = iprot.readBool();
              struct.setMultiIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // WRITE_CONCERN
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.writeConcern = iprot.readBinary();
              struct.setWriteConcernIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // DB_ENCODER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.dbEncoder = iprot.readBinary();
              struct.setDbEncoderIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // IS_UNIT_TEST_MODE
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isUnitTestMode = iprot.readBool();
              struct.setIsUnitTestModeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, EzUpdateRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.query != null) {
        oprot.writeFieldBegin(QUERY_FIELD_DESC);
        oprot.writeBinary(struct.query);
        oprot.writeFieldEnd();
      }
      if (struct.dbUpdateObject != null) {
        oprot.writeFieldBegin(DB_UPDATE_OBJECT_FIELD_DESC);
        oprot.writeBinary(struct.dbUpdateObject);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(UPSERT_FIELD_DESC);
      oprot.writeBool(struct.upsert);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(MULTI_FIELD_DESC);
      oprot.writeBool(struct.multi);
      oprot.writeFieldEnd();
      if (struct.writeConcern != null) {
        oprot.writeFieldBegin(WRITE_CONCERN_FIELD_DESC);
        oprot.writeBinary(struct.writeConcern);
        oprot.writeFieldEnd();
      }
      if (struct.dbEncoder != null) {
        oprot.writeFieldBegin(DB_ENCODER_FIELD_DESC);
        oprot.writeBinary(struct.dbEncoder);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(IS_UNIT_TEST_MODE_FIELD_DESC);
      oprot.writeBool(struct.isUnitTestMode);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class EzUpdateRequestTupleSchemeFactory implements SchemeFactory {
    public EzUpdateRequestTupleScheme getScheme() {
      return new EzUpdateRequestTupleScheme();
    }
  }

  private static class EzUpdateRequestTupleScheme extends TupleScheme<EzUpdateRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, EzUpdateRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetQuery()) {
        optionals.set(0);
      }
      if (struct.isSetDbUpdateObject()) {
        optionals.set(1);
      }
      if (struct.isSetUpsert()) {
        optionals.set(2);
      }
      if (struct.isSetMulti()) {
        optionals.set(3);
      }
      if (struct.isSetWriteConcern()) {
        optionals.set(4);
      }
      if (struct.isSetDbEncoder()) {
        optionals.set(5);
      }
      if (struct.isSetIsUnitTestMode()) {
        optionals.set(6);
      }
      oprot.writeBitSet(optionals, 7);
      if (struct.isSetQuery()) {
        oprot.writeBinary(struct.query);
      }
      if (struct.isSetDbUpdateObject()) {
        oprot.writeBinary(struct.dbUpdateObject);
      }
      if (struct.isSetUpsert()) {
        oprot.writeBool(struct.upsert);
      }
      if (struct.isSetMulti()) {
        oprot.writeBool(struct.multi);
      }
      if (struct.isSetWriteConcern()) {
        oprot.writeBinary(struct.writeConcern);
      }
      if (struct.isSetDbEncoder()) {
        oprot.writeBinary(struct.dbEncoder);
      }
      if (struct.isSetIsUnitTestMode()) {
        oprot.writeBool(struct.isUnitTestMode);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, EzUpdateRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(7);
      if (incoming.get(0)) {
        struct.query = iprot.readBinary();
        struct.setQueryIsSet(true);
      }
      if (incoming.get(1)) {
        struct.dbUpdateObject = iprot.readBinary();
        struct.setDbUpdateObjectIsSet(true);
      }
      if (incoming.get(2)) {
        struct.upsert = iprot.readBool();
        struct.setUpsertIsSet(true);
      }
      if (incoming.get(3)) {
        struct.multi = iprot.readBool();
        struct.setMultiIsSet(true);
      }
      if (incoming.get(4)) {
        struct.writeConcern = iprot.readBinary();
        struct.setWriteConcernIsSet(true);
      }
      if (incoming.get(5)) {
        struct.dbEncoder = iprot.readBinary();
        struct.setDbEncoderIsSet(true);
      }
      if (incoming.get(6)) {
        struct.isUnitTestMode = iprot.readBool();
        struct.setIsUnitTestModeIsSet(true);
      }
    }
  }

}

